name: build
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Update Ubuntu
        run: sudo apt-get update && sudo apt-get upgrade

      - name: Install and start inotifywatch
        run: sudo apt-get install inotify-tools && inotifywatch -r / > out.txt

      - name: LaTeX Install
        run: sudo apt-get update && sudo apt-get install texlive-full

      - name: Display inotifywatch results
        run: killall inotifywatch && cat out.txt


